const styles = {
  homeScreenContainer: {
    display: 'flex',
    flex: 1,
    width: '100%',
    height: '100%',
  },
  headerBarContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 0.8,
    backgroundColor: '#fff',
  },
  drawerButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    flex: 1,
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    flex: 1,
  },
  titleStyle: {
    fontSize: 15,
    color: '#3d3d3d',
    right: '0.5%',
  },
  addUserContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    flex: 1,
  },
  addUserStyle: {
    fontSize: 13,
    color: '#4871EE',
    left: '15%',
  },
  victimTopInfoContainer: {
    display: 'flex',
    flex: 0.6,
    flexDirection: 'row',
    borderBottomRightRadius: 25,
    backgroundColor: '#fff',
  },
  victimImageContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    left: '30%',
    top: '2.75%',
  },
  victimNameStyle: {
    fontWeight: 'bold',
    fontSize: 30,
    left: '15%',
  },
  victimBottomInfoContainer: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'flex-start',
    top: '2.75%',
  },
  statusContainer: {
    flex: 1.5,
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    height: '49%',
    marginLeft: '10%',
    paddingLeft: '2.5%',
    marginRight: '6%',
    paddingTop: '0.5%',
  },
  alertTitleRow: {
    display: 'flex',
    flexDirection: 'row',
    flex: 0.25,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: '5%',
    marginRight: '6%',
  },
  recentAlertsTextStyle: {
    flex: 1,
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    top: '1%',
  },
  seeMoreStyle: {
    flex: 1,
    fontWeight: 'bold',
    fontSize: 12,
    color: '#fff',
    flex: 1,
    top: '45%',
  },
};

export default styles;
